#!/bin/bash

if [[ -f /usr/bin/firefox ]]; then
	cp -f /etc/manjaro-firefox.ini /usr/lib/firefox/distribution/distribution.ini
fi

if [[ -f /usr/bin/firefox-developer-edition ]]; then
	cp -f /etc/manjaro-firefox.ini /usr/lib/firefox-developer-edition/distribution/distribution.ini
	sed -i 's/Firefox/Firefox Developer Edition/;s/firefox/firefox-developer-edition/' /usr/lib/firefox-developer-edition/distribution/distribution.ini
fi

